name: Cleanup

on:
  schedule:
    - cron: '45 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync dev branch with master branch
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ github.repository }}
          source_branch: master
          destination_branch: dev
          github_token: ${{ secrets.SYNC_BRANCHES_PAT }}